# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
