# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170330_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenuto',
            name='immagine_box_1',
            field=models.FileField(blank=True, max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='immagine_box_2',
            field=models.FileField(blank=True, max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='immagine_box_3',
            field=models.FileField(blank=True, max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='immagine_box_4',
            field=models.FileField(blank=True, max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='immagine',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
    ]
