# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170330_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine_box_1', models.FileField(blank=True, max_length=500, upload_to='')),
                ('immagine_box_2', models.FileField(blank=True, max_length=500, upload_to='')),
                ('immagine_box_3', models.FileField(blank=True, max_length=500, upload_to='')),
                ('immagine_box_4', models.FileField(blank=True, max_length=500, upload_to='')),
                ('testo_about', models.TextField(blank=True, max_length=3000)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Modifica il contenuto della pagina About',
            },
        ),
    ]
