# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.FileField(blank=True, max_length=500, upload_to='')),
                ('logo', models.FileField(blank=True, max_length=500, upload_to='')),
                ('titolo_work', models.TextField(blank=True, max_length=100)),
                ('descrizione_work', models.TextField(blank=True, max_length=3000)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='titolo_about',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
