# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170512_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Modifica il contenuto della pagina Work'},
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='cambia_automaticamente_gallery',
        ),
        migrations.AddField(
            model_name='contenuto',
            name='sottotesto_home',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='contenuto',
            name='sottotitolo_home',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contenuto',
            name='testo_home',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='contenuto',
            name='titolo_home',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
