# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170513_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenuto',
            name='immagine_box_1',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='immagine_box_2',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='immagine_box_3',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='immagine_box_4',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='testo_box_1',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='testo_box_2',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='testo_box_3',
        ),
        migrations.RemoveField(
            model_name='contenuto',
            name='testo_box_4',
        ),
        migrations.AddField(
            model_name='about',
            name='testo_box_1',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='about',
            name='testo_box_2',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='about',
            name='testo_box_3',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='about',
            name='testo_box_4',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
