# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170513_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='immagine_box_5',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='testo_box_5',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
