# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170513_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
