# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170517_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='logo',
        ),
    ]
