# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_work_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azienda', models.TextField(blank=True, max_length=100)),
                ('indirizzo_azienda', models.TextField(blank=True, max_length=100)),
                ('civico_azienda', models.TextField(blank=True, max_length=100)),
                ('cap', models.TextField(blank=True, max_length=5)),
                ('comune', models.TextField(blank=True, max_length=100)),
                ('provincia', models.TextField(blank=True, max_length=100)),
                ('tel', models.TextField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Contatti',
                'verbose_name_plural': 'Modifica i dati di contatto',
            },
        ),
    ]
