# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cap',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='contact',
            name='civico_azienda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='indirizzo_azienda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nome_azienda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
