# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170522_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='numero_rea',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='contact',
            name='p_iva',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='contact',
            name='pec',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
